name: Sync
on:
  push:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
    sync:
        runs-on: ubuntu-latest
        steps:
        - name: 'Checking'
          uses: actions/checkout@v3
          
        - name: 'Sync fork'
#          uses: repo-sync/github-sync@v2
#          with:
#            source_repo: "https://github.com/TBXark/ChatGPT-Telegram-Workers"
#            source_branch: "master"
#            destination_branch: "master"
#            github_token: ${{ secrets.COMMIT_SECRET }}
          env:
            USER_NAME: goodffd
            USER_EMAIL: goodffd@gmail.com
          run: |
            git config --local user.name $USER_NAME
            git config --local user.email $USER_EMAIL
            git pull --unshallow
            git remote add upstream https://github.com/TBXark/ChatGPT-Telegram-Workers.git
            git fetch upstream
            git checkout master
            git merge --no-edit upstream/master
            git push origin master
            git fetch upstream --tags
            git push --tags
